// @generated by tools/scripts/gen_fused_hash.py; do not edit by hand.
//! MD5 and SHA-256 (SHA extensions) blocks with their serial chains
//! interleaved in program order, so one out-of-order core runs both at
//! once. Each step and round group is the same arithmetic as `md5::compress`
//! and `sha256::compress_sha_ni`; the tests compare the results with them.
#![cfg(target_arch = "x86_64")]
use crate::md5::K as MD5_K;
use crate::sha256::K as SHA_K;
use std::arch::x86_64::*;

#[inline(always)]
fn words(block: &[u8; 64]) -> [u32; 16] {
    let mut m = [0u32; 16];
    for (word, bytes) in m.iter_mut().zip(block.as_chunks::<4>().0) {
        *word = u32::from_le_bytes(*bytes);
    }
    m
}

// MD5 steps exactly as in `md5::compress` (see that module for the round
// function forms).
macro_rules! step {
    ($a:ident, $b:ident, $f:expr, $k:expr, $m:expr, $s:expr) => {
        $a = $b.wrapping_add(
            $a.wrapping_add($k)
                .wrapping_add($m)
                .wrapping_add($f)
                .rotate_left($s),
        );
    };
}
macro_rules! ff {
    ($a:ident, $b:ident, $c:ident, $d:ident, $m:expr, $i:expr, $s:expr) => {
        step!(
            $a,
            $b,
            $d ^ ($b & ($c ^ $d)),
            std::hint::black_box(&MD5_K)[$i],
            $m,
            $s
        )
    };
}
macro_rules! gg {
    ($a:ident, $b:ident, $c:ident, $d:ident, $m:expr, $i:expr, $s:expr) => {
        $a = $b.wrapping_add(
            $a.wrapping_add(std::hint::black_box(&MD5_K)[$i])
                .wrapping_add($m)
                .wrapping_add($c & !$d)
                .wrapping_add($b & $d)
                .rotate_left($s),
        );
    };
}
macro_rules! hh {
    ($a:ident, $b:ident, $c:ident, $d:ident, $m:expr, $i:expr, $s:expr) => {
        step!(
            $a,
            $b,
            $b ^ ($c ^ $d),
            std::hint::black_box(&MD5_K)[$i],
            $m,
            $s
        )
    };
}
macro_rules! ii {
    ($a:ident, $b:ident, $c:ident, $d:ident, $m:expr, $i:expr, $s:expr) => {
        step!(
            $a,
            $b,
            $c ^ ($b | !$d),
            std::hint::black_box(&MD5_K)[$i],
            $m,
            $s
        )
    };
}
macro_rules! rounds {
    ($abef:ident, $cdgh:ident, $m:expr, $i:expr) => {{
        let message = _mm_add_epi32($m, _mm_loadu_si128(SHA_K.as_ptr().add(4 * $i).cast()));
        $cdgh = _mm_sha256rnds2_epu32($cdgh, $abef, message);
        $abef = _mm_sha256rnds2_epu32($abef, $cdgh, _mm_shuffle_epi32(message, 0x0e));
    }};
}
macro_rules! extend {
    ($next:ident, $cur:ident, $prev:ident) => {
        $next = _mm_sha256msg2_epu32(_mm_add_epi32($next, _mm_alignr_epi8($cur, $prev, 4)), $cur);
    };
}

/// 1 MD5 block(s) interleaved with 2 SHA-256 block(s) per unit.
#[target_feature(enable = "sha,sse2,ssse3,sse4.1")]
pub(crate) unsafe fn md5_1_sha_2(
    md5: &mut [u32; 4],
    md5_blocks: &[[u8; 64]],
    sha: &mut [u32; 8],
    sha_blocks: &[[u8; 64]],
) {
    assert_eq!(md5_blocks.len() * 2, sha_blocks.len());
    let byte_swap = _mm_set_epi64x(0x0c0d0e0f08090a0b, 0x0405060700010203);
    // SAFETY (all SIMD loads/stores): pointers come from live arrays of
    // at least 16 bytes; loads and stores are unaligned.
    let load = |block: &[u8; 64], i: usize| {
        _mm_shuffle_epi8(
            _mm_loadu_si128(block.as_ptr().add(16 * i).cast()),
            byte_swap,
        )
    };
    let dcba = _mm_loadu_si128(sha.as_ptr().cast());
    let hgfe = _mm_loadu_si128(sha.as_ptr().add(4).cast());
    let cdab = _mm_shuffle_epi32(dcba, 0xb1);
    let efgh = _mm_shuffle_epi32(hgfe, 0x1b);
    let mut abef = _mm_alignr_epi8(cdab, efgh, 8);
    let mut cdgh = _mm_blend_epi16(efgh, cdab, 0xf0);
    let [mut a, mut b, mut c, mut d] = *md5;
    for (m, s) in md5_blocks
        .as_chunks::<1>()
        .0
        .iter()
        .zip(sha_blocks.as_chunks::<2>().0.iter())
    {
        let m0 = words(&m[0]);
        let saved = (a, b, c, d);
        ff!(a, b, c, d, m0[0], 0, 7);
        ff!(d, a, b, c, m0[1], 1, 12);
        let (abef_saved0, cdgh_saved0) = (abef, cdgh);
        let mut w0_0 = load(&s[0], 0);
        let mut w0_1 = load(&s[0], 1);
        let mut w0_2 = load(&s[0], 2);
        let mut w0_3 = load(&s[0], 3);
        rounds!(abef, cdgh, w0_0, 0);
        ff!(c, d, a, b, m0[2], 2, 17);
        ff!(b, c, d, a, m0[3], 3, 22);
        rounds!(abef, cdgh, w0_1, 1);
        w0_0 = _mm_sha256msg1_epu32(w0_0, w0_1);
        ff!(a, b, c, d, m0[4], 4, 7);
        ff!(d, a, b, c, m0[5], 5, 12);
        rounds!(abef, cdgh, w0_2, 2);
        w0_1 = _mm_sha256msg1_epu32(w0_1, w0_2);
        ff!(c, d, a, b, m0[6], 6, 17);
        ff!(b, c, d, a, m0[7], 7, 22);
        rounds!(abef, cdgh, w0_3, 3);
        extend!(w0_0, w0_3, w0_2);
        w0_2 = _mm_sha256msg1_epu32(w0_2, w0_3);
        ff!(a, b, c, d, m0[8], 8, 7);
        ff!(d, a, b, c, m0[9], 9, 12);
        rounds!(abef, cdgh, w0_0, 4);
        extend!(w0_1, w0_0, w0_3);
        w0_3 = _mm_sha256msg1_epu32(w0_3, w0_0);
        ff!(c, d, a, b, m0[10], 10, 17);
        ff!(b, c, d, a, m0[11], 11, 22);
        rounds!(abef, cdgh, w0_1, 5);
        extend!(w0_2, w0_1, w0_0);
        w0_0 = _mm_sha256msg1_epu32(w0_0, w0_1);
        ff!(a, b, c, d, m0[12], 12, 7);
        ff!(d, a, b, c, m0[13], 13, 12);
        rounds!(abef, cdgh, w0_2, 6);
        extend!(w0_3, w0_2, w0_1);
        w0_1 = _mm_sha256msg1_epu32(w0_1, w0_2);
        ff!(c, d, a, b, m0[14], 14, 17);
        ff!(b, c, d, a, m0[15], 15, 22);
        rounds!(abef, cdgh, w0_3, 7);
        extend!(w0_0, w0_3, w0_2);
        w0_2 = _mm_sha256msg1_epu32(w0_2, w0_3);
        gg!(a, b, c, d, m0[1], 16, 5);
        gg!(d, a, b, c, m0[6], 17, 9);
        rounds!(abef, cdgh, w0_0, 8);
        extend!(w0_1, w0_0, w0_3);
        w0_3 = _mm_sha256msg1_epu32(w0_3, w0_0);
        gg!(c, d, a, b, m0[11], 18, 14);
        gg!(b, c, d, a, m0[0], 19, 20);
        rounds!(abef, cdgh, w0_1, 9);
        extend!(w0_2, w0_1, w0_0);
        w0_0 = _mm_sha256msg1_epu32(w0_0, w0_1);
        gg!(a, b, c, d, m0[5], 20, 5);
        gg!(d, a, b, c, m0[10], 21, 9);
        rounds!(abef, cdgh, w0_2, 10);
        extend!(w0_3, w0_2, w0_1);
        w0_1 = _mm_sha256msg1_epu32(w0_1, w0_2);
        gg!(c, d, a, b, m0[15], 22, 14);
        gg!(b, c, d, a, m0[4], 23, 20);
        rounds!(abef, cdgh, w0_3, 11);
        extend!(w0_0, w0_3, w0_2);
        w0_2 = _mm_sha256msg1_epu32(w0_2, w0_3);
        gg!(a, b, c, d, m0[9], 24, 5);
        gg!(d, a, b, c, m0[14], 25, 9);
        rounds!(abef, cdgh, w0_0, 12);
        extend!(w0_1, w0_0, w0_3);
        w0_3 = _mm_sha256msg1_epu32(w0_3, w0_0);
        gg!(c, d, a, b, m0[3], 26, 14);
        gg!(b, c, d, a, m0[8], 27, 20);
        rounds!(abef, cdgh, w0_1, 13);
        extend!(w0_2, w0_1, w0_0);
        gg!(a, b, c, d, m0[13], 28, 5);
        gg!(d, a, b, c, m0[2], 29, 9);
        rounds!(abef, cdgh, w0_2, 14);
        extend!(w0_3, w0_2, w0_1);
        gg!(c, d, a, b, m0[7], 30, 14);
        gg!(b, c, d, a, m0[12], 31, 20);
        rounds!(abef, cdgh, w0_3, 15);
        abef = _mm_add_epi32(abef, abef_saved0);
        cdgh = _mm_add_epi32(cdgh, cdgh_saved0);
        hh!(a, b, c, d, m0[5], 32, 4);
        hh!(d, a, b, c, m0[8], 33, 11);
        let (abef_saved1, cdgh_saved1) = (abef, cdgh);
        let mut w1_0 = load(&s[1], 0);
        let mut w1_1 = load(&s[1], 1);
        let mut w1_2 = load(&s[1], 2);
        let mut w1_3 = load(&s[1], 3);
        rounds!(abef, cdgh, w1_0, 0);
        hh!(c, d, a, b, m0[11], 34, 16);
        hh!(b, c, d, a, m0[14], 35, 23);
        rounds!(abef, cdgh, w1_1, 1);
        w1_0 = _mm_sha256msg1_epu32(w1_0, w1_1);
        hh!(a, b, c, d, m0[1], 36, 4);
        hh!(d, a, b, c, m0[4], 37, 11);
        rounds!(abef, cdgh, w1_2, 2);
        w1_1 = _mm_sha256msg1_epu32(w1_1, w1_2);
        hh!(c, d, a, b, m0[7], 38, 16);
        hh!(b, c, d, a, m0[10], 39, 23);
        rounds!(abef, cdgh, w1_3, 3);
        extend!(w1_0, w1_3, w1_2);
        w1_2 = _mm_sha256msg1_epu32(w1_2, w1_3);
        hh!(a, b, c, d, m0[13], 40, 4);
        hh!(d, a, b, c, m0[0], 41, 11);
        rounds!(abef, cdgh, w1_0, 4);
        extend!(w1_1, w1_0, w1_3);
        w1_3 = _mm_sha256msg1_epu32(w1_3, w1_0);
        hh!(c, d, a, b, m0[3], 42, 16);
        hh!(b, c, d, a, m0[6], 43, 23);
        rounds!(abef, cdgh, w1_1, 5);
        extend!(w1_2, w1_1, w1_0);
        w1_0 = _mm_sha256msg1_epu32(w1_0, w1_1);
        hh!(a, b, c, d, m0[9], 44, 4);
        hh!(d, a, b, c, m0[12], 45, 11);
        rounds!(abef, cdgh, w1_2, 6);
        extend!(w1_3, w1_2, w1_1);
        w1_1 = _mm_sha256msg1_epu32(w1_1, w1_2);
        hh!(c, d, a, b, m0[15], 46, 16);
        hh!(b, c, d, a, m0[2], 47, 23);
        rounds!(abef, cdgh, w1_3, 7);
        extend!(w1_0, w1_3, w1_2);
        w1_2 = _mm_sha256msg1_epu32(w1_2, w1_3);
        ii!(a, b, c, d, m0[0], 48, 6);
        ii!(d, a, b, c, m0[7], 49, 10);
        rounds!(abef, cdgh, w1_0, 8);
        extend!(w1_1, w1_0, w1_3);
        w1_3 = _mm_sha256msg1_epu32(w1_3, w1_0);
        ii!(c, d, a, b, m0[14], 50, 15);
        ii!(b, c, d, a, m0[5], 51, 21);
        rounds!(abef, cdgh, w1_1, 9);
        extend!(w1_2, w1_1, w1_0);
        w1_0 = _mm_sha256msg1_epu32(w1_0, w1_1);
        ii!(a, b, c, d, m0[12], 52, 6);
        ii!(d, a, b, c, m0[3], 53, 10);
        rounds!(abef, cdgh, w1_2, 10);
        extend!(w1_3, w1_2, w1_1);
        w1_1 = _mm_sha256msg1_epu32(w1_1, w1_2);
        ii!(c, d, a, b, m0[10], 54, 15);
        ii!(b, c, d, a, m0[1], 55, 21);
        rounds!(abef, cdgh, w1_3, 11);
        extend!(w1_0, w1_3, w1_2);
        w1_2 = _mm_sha256msg1_epu32(w1_2, w1_3);
        ii!(a, b, c, d, m0[8], 56, 6);
        ii!(d, a, b, c, m0[15], 57, 10);
        rounds!(abef, cdgh, w1_0, 12);
        extend!(w1_1, w1_0, w1_3);
        w1_3 = _mm_sha256msg1_epu32(w1_3, w1_0);
        ii!(c, d, a, b, m0[6], 58, 15);
        ii!(b, c, d, a, m0[13], 59, 21);
        rounds!(abef, cdgh, w1_1, 13);
        extend!(w1_2, w1_1, w1_0);
        ii!(a, b, c, d, m0[4], 60, 6);
        ii!(d, a, b, c, m0[11], 61, 10);
        rounds!(abef, cdgh, w1_2, 14);
        extend!(w1_3, w1_2, w1_1);
        ii!(c, d, a, b, m0[2], 62, 15);
        ii!(b, c, d, a, m0[9], 63, 21);
        a = a.wrapping_add(saved.0);
        b = b.wrapping_add(saved.1);
        c = c.wrapping_add(saved.2);
        d = d.wrapping_add(saved.3);
        rounds!(abef, cdgh, w1_3, 15);
        abef = _mm_add_epi32(abef, abef_saved1);
        cdgh = _mm_add_epi32(cdgh, cdgh_saved1);
    }
    *md5 = [a, b, c, d];
    let feba = _mm_shuffle_epi32(abef, 0x1b);
    let dchg = _mm_shuffle_epi32(cdgh, 0xb1);
    _mm_storeu_si128(sha.as_mut_ptr().cast(), _mm_blend_epi16(feba, dchg, 0xf0));
    _mm_storeu_si128(
        sha.as_mut_ptr().add(4).cast(),
        _mm_alignr_epi8(dchg, feba, 8),
    );
}

/// 3 MD5 block(s) interleaved with 4 SHA-256 block(s) per unit.
#[target_feature(enable = "sha,sse2,ssse3,sse4.1")]
pub(crate) unsafe fn md5_3_sha_4(
    md5: &mut [u32; 4],
    md5_blocks: &[[u8; 64]],
    sha: &mut [u32; 8],
    sha_blocks: &[[u8; 64]],
) {
    assert_eq!(md5_blocks.len() * 4, sha_blocks.len() * 3);
    let byte_swap = _mm_set_epi64x(0x0c0d0e0f08090a0b, 0x0405060700010203);
    // SAFETY (all SIMD loads/stores): pointers come from live arrays of
    // at least 16 bytes; loads and stores are unaligned.
    let load = |block: &[u8; 64], i: usize| {
        _mm_shuffle_epi8(
            _mm_loadu_si128(block.as_ptr().add(16 * i).cast()),
            byte_swap,
        )
    };
    let dcba = _mm_loadu_si128(sha.as_ptr().cast());
    let hgfe = _mm_loadu_si128(sha.as_ptr().add(4).cast());
    let cdab = _mm_shuffle_epi32(dcba, 0xb1);
    let efgh = _mm_shuffle_epi32(hgfe, 0x1b);
    let mut abef = _mm_alignr_epi8(cdab, efgh, 8);
    let mut cdgh = _mm_blend_epi16(efgh, cdab, 0xf0);
    let [mut a, mut b, mut c, mut d] = *md5;
    for (m, s) in md5_blocks
        .as_chunks::<3>()
        .0
        .iter()
        .zip(sha_blocks.as_chunks::<4>().0.iter())
    {
        let m0 = words(&m[0]);
        let m1 = words(&m[1]);
        let m2 = words(&m[2]);
        let saved = (a, b, c, d);
        ff!(a, b, c, d, m0[0], 0, 7);
        ff!(d, a, b, c, m0[1], 1, 12);
        ff!(c, d, a, b, m0[2], 2, 17);
        let (abef_saved0, cdgh_saved0) = (abef, cdgh);
        let mut w0_0 = load(&s[0], 0);
        let mut w0_1 = load(&s[0], 1);
        let mut w0_2 = load(&s[0], 2);
        let mut w0_3 = load(&s[0], 3);
        rounds!(abef, cdgh, w0_0, 0);
        ff!(b, c, d, a, m0[3], 3, 22);
        ff!(a, b, c, d, m0[4], 4, 7);
        ff!(d, a, b, c, m0[5], 5, 12);
        rounds!(abef, cdgh, w0_1, 1);
        w0_0 = _mm_sha256msg1_epu32(w0_0, w0_1);
        ff!(c, d, a, b, m0[6], 6, 17);
        ff!(b, c, d, a, m0[7], 7, 22);
        ff!(a, b, c, d, m0[8], 8, 7);
        rounds!(abef, cdgh, w0_2, 2);
        w0_1 = _mm_sha256msg1_epu32(w0_1, w0_2);
        ff!(d, a, b, c, m0[9], 9, 12);
        ff!(c, d, a, b, m0[10], 10, 17);
        ff!(b, c, d, a, m0[11], 11, 22);
        rounds!(abef, cdgh, w0_3, 3);
        extend!(w0_0, w0_3, w0_2);
        w0_2 = _mm_sha256msg1_epu32(w0_2, w0_3);
        ff!(a, b, c, d, m0[12], 12, 7);
        ff!(d, a, b, c, m0[13], 13, 12);
        ff!(c, d, a, b, m0[14], 14, 17);
        rounds!(abef, cdgh, w0_0, 4);
        extend!(w0_1, w0_0, w0_3);
        w0_3 = _mm_sha256msg1_epu32(w0_3, w0_0);
        ff!(b, c, d, a, m0[15], 15, 22);
        gg!(a, b, c, d, m0[1], 16, 5);
        gg!(d, a, b, c, m0[6], 17, 9);
        rounds!(abef, cdgh, w0_1, 5);
        extend!(w0_2, w0_1, w0_0);
        w0_0 = _mm_sha256msg1_epu32(w0_0, w0_1);
        gg!(c, d, a, b, m0[11], 18, 14);
        gg!(b, c, d, a, m0[0], 19, 20);
        gg!(a, b, c, d, m0[5], 20, 5);
        rounds!(abef, cdgh, w0_2, 6);
        extend!(w0_3, w0_2, w0_1);
        w0_1 = _mm_sha256msg1_epu32(w0_1, w0_2);
        gg!(d, a, b, c, m0[10], 21, 9);
        gg!(c, d, a, b, m0[15], 22, 14);
        gg!(b, c, d, a, m0[4], 23, 20);
        rounds!(abef, cdgh, w0_3, 7);
        extend!(w0_0, w0_3, w0_2);
        w0_2 = _mm_sha256msg1_epu32(w0_2, w0_3);
        gg!(a, b, c, d, m0[9], 24, 5);
        gg!(d, a, b, c, m0[14], 25, 9);
        gg!(c, d, a, b, m0[3], 26, 14);
        rounds!(abef, cdgh, w0_0, 8);
        extend!(w0_1, w0_0, w0_3);
        w0_3 = _mm_sha256msg1_epu32(w0_3, w0_0);
        gg!(b, c, d, a, m0[8], 27, 20);
        gg!(a, b, c, d, m0[13], 28, 5);
        gg!(d, a, b, c, m0[2], 29, 9);
        rounds!(abef, cdgh, w0_1, 9);
        extend!(w0_2, w0_1, w0_0);
        w0_0 = _mm_sha256msg1_epu32(w0_0, w0_1);
        gg!(c, d, a, b, m0[7], 30, 14);
        gg!(b, c, d, a, m0[12], 31, 20);
        hh!(a, b, c, d, m0[5], 32, 4);
        rounds!(abef, cdgh, w0_2, 10);
        extend!(w0_3, w0_2, w0_1);
        w0_1 = _mm_sha256msg1_epu32(w0_1, w0_2);
        hh!(d, a, b, c, m0[8], 33, 11);
        hh!(c, d, a, b, m0[11], 34, 16);
        hh!(b, c, d, a, m0[14], 35, 23);
        rounds!(abef, cdgh, w0_3, 11);
        extend!(w0_0, w0_3, w0_2);
        w0_2 = _mm_sha256msg1_epu32(w0_2, w0_3);
        hh!(a, b, c, d, m0[1], 36, 4);
        hh!(d, a, b, c, m0[4], 37, 11);
        hh!(c, d, a, b, m0[7], 38, 16);
        rounds!(abef, cdgh, w0_0, 12);
        extend!(w0_1, w0_0, w0_3);
        w0_3 = _mm_sha256msg1_epu32(w0_3, w0_0);
        hh!(b, c, d, a, m0[10], 39, 23);
        hh!(a, b, c, d, m0[13], 40, 4);
        hh!(d, a, b, c, m0[0], 41, 11);
        rounds!(abef, cdgh, w0_1, 13);
        extend!(w0_2, w0_1, w0_0);
        hh!(c, d, a, b, m0[3], 42, 16);
        hh!(b, c, d, a, m0[6], 43, 23);
        hh!(a, b, c, d, m0[9], 44, 4);
        rounds!(abef, cdgh, w0_2, 14);
        extend!(w0_3, w0_2, w0_1);
        hh!(d, a, b, c, m0[12], 45, 11);
        hh!(c, d, a, b, m0[15], 46, 16);
        hh!(b, c, d, a, m0[2], 47, 23);
        rounds!(abef, cdgh, w0_3, 15);
        abef = _mm_add_epi32(abef, abef_saved0);
        cdgh = _mm_add_epi32(cdgh, cdgh_saved0);
        ii!(a, b, c, d, m0[0], 48, 6);
        ii!(d, a, b, c, m0[7], 49, 10);
        ii!(c, d, a, b, m0[14], 50, 15);
        let (abef_saved1, cdgh_saved1) = (abef, cdgh);
        let mut w1_0 = load(&s[1], 0);
        let mut w1_1 = load(&s[1], 1);
        let mut w1_2 = load(&s[1], 2);
        let mut w1_3 = load(&s[1], 3);
        rounds!(abef, cdgh, w1_0, 0);
        ii!(b, c, d, a, m0[5], 51, 21);
        ii!(a, b, c, d, m0[12], 52, 6);
        ii!(d, a, b, c, m0[3], 53, 10);
        rounds!(abef, cdgh, w1_1, 1);
        w1_0 = _mm_sha256msg1_epu32(w1_0, w1_1);
        ii!(c, d, a, b, m0[10], 54, 15);
        ii!(b, c, d, a, m0[1], 55, 21);
        ii!(a, b, c, d, m0[8], 56, 6);
        rounds!(abef, cdgh, w1_2, 2);
        w1_1 = _mm_sha256msg1_epu32(w1_1, w1_2);
        ii!(d, a, b, c, m0[15], 57, 10);
        ii!(c, d, a, b, m0[6], 58, 15);
        ii!(b, c, d, a, m0[13], 59, 21);
        rounds!(abef, cdgh, w1_3, 3);
        extend!(w1_0, w1_3, w1_2);
        w1_2 = _mm_sha256msg1_epu32(w1_2, w1_3);
        ii!(a, b, c, d, m0[4], 60, 6);
        ii!(d, a, b, c, m0[11], 61, 10);
        ii!(c, d, a, b, m0[2], 62, 15);
        rounds!(abef, cdgh, w1_0, 4);
        extend!(w1_1, w1_0, w1_3);
        w1_3 = _mm_sha256msg1_epu32(w1_3, w1_0);
        ii!(b, c, d, a, m0[9], 63, 21);
        a = a.wrapping_add(saved.0);
        b = b.wrapping_add(saved.1);
        c = c.wrapping_add(saved.2);
        d = d.wrapping_add(saved.3);
        let saved_blk = (a, b, c, d);
        ff!(a, b, c, d, m1[0], 0, 7);
        ff!(d, a, b, c, m1[1], 1, 12);
        rounds!(abef, cdgh, w1_1, 5);
        extend!(w1_2, w1_1, w1_0);
        w1_0 = _mm_sha256msg1_epu32(w1_0, w1_1);
        ff!(c, d, a, b, m1[2], 2, 17);
        ff!(b, c, d, a, m1[3], 3, 22);
        ff!(a, b, c, d, m1[4], 4, 7);
        rounds!(abef, cdgh, w1_2, 6);
        extend!(w1_3, w1_2, w1_1);
        w1_1 = _mm_sha256msg1_epu32(w1_1, w1_2);
        ff!(d, a, b, c, m1[5], 5, 12);
        ff!(c, d, a, b, m1[6], 6, 17);
        ff!(b, c, d, a, m1[7], 7, 22);
        rounds!(abef, cdgh, w1_3, 7);
        extend!(w1_0, w1_3, w1_2);
        w1_2 = _mm_sha256msg1_epu32(w1_2, w1_3);
        ff!(a, b, c, d, m1[8], 8, 7);
        ff!(d, a, b, c, m1[9], 9, 12);
        ff!(c, d, a, b, m1[10], 10, 17);
        rounds!(abef, cdgh, w1_0, 8);
        extend!(w1_1, w1_0, w1_3);
        w1_3 = _mm_sha256msg1_epu32(w1_3, w1_0);
        ff!(b, c, d, a, m1[11], 11, 22);
        ff!(a, b, c, d, m1[12], 12, 7);
        ff!(d, a, b, c, m1[13], 13, 12);
        rounds!(abef, cdgh, w1_1, 9);
        extend!(w1_2, w1_1, w1_0);
        w1_0 = _mm_sha256msg1_epu32(w1_0, w1_1);
        ff!(c, d, a, b, m1[14], 14, 17);
        ff!(b, c, d, a, m1[15], 15, 22);
        gg!(a, b, c, d, m1[1], 16, 5);
        rounds!(abef, cdgh, w1_2, 10);
        extend!(w1_3, w1_2, w1_1);
        w1_1 = _mm_sha256msg1_epu32(w1_1, w1_2);
        gg!(d, a, b, c, m1[6], 17, 9);
        gg!(c, d, a, b, m1[11], 18, 14);
        gg!(b, c, d, a, m1[0], 19, 20);
        rounds!(abef, cdgh, w1_3, 11);
        extend!(w1_0, w1_3, w1_2);
        w1_2 = _mm_sha256msg1_epu32(w1_2, w1_3);
        gg!(a, b, c, d, m1[5], 20, 5);
        gg!(d, a, b, c, m1[10], 21, 9);
        gg!(c, d, a, b, m1[15], 22, 14);
        rounds!(abef, cdgh, w1_0, 12);
        extend!(w1_1, w1_0, w1_3);
        w1_3 = _mm_sha256msg1_epu32(w1_3, w1_0);
        gg!(b, c, d, a, m1[4], 23, 20);
        gg!(a, b, c, d, m1[9], 24, 5);
        gg!(d, a, b, c, m1[14], 25, 9);
        rounds!(abef, cdgh, w1_1, 13);
        extend!(w1_2, w1_1, w1_0);
        gg!(c, d, a, b, m1[3], 26, 14);
        gg!(b, c, d, a, m1[8], 27, 20);
        gg!(a, b, c, d, m1[13], 28, 5);
        rounds!(abef, cdgh, w1_2, 14);
        extend!(w1_3, w1_2, w1_1);
        gg!(d, a, b, c, m1[2], 29, 9);
        gg!(c, d, a, b, m1[7], 30, 14);
        gg!(b, c, d, a, m1[12], 31, 20);
        rounds!(abef, cdgh, w1_3, 15);
        abef = _mm_add_epi32(abef, abef_saved1);
        cdgh = _mm_add_epi32(cdgh, cdgh_saved1);
        hh!(a, b, c, d, m1[5], 32, 4);
        hh!(d, a, b, c, m1[8], 33, 11);
        hh!(c, d, a, b, m1[11], 34, 16);
        let (abef_saved2, cdgh_saved2) = (abef, cdgh);
        let mut w2_0 = load(&s[2], 0);
        let mut w2_1 = load(&s[2], 1);
        let mut w2_2 = load(&s[2], 2);
        let mut w2_3 = load(&s[2], 3);
        rounds!(abef, cdgh, w2_0, 0);
        hh!(b, c, d, a, m1[14], 35, 23);
        hh!(a, b, c, d, m1[1], 36, 4);
        hh!(d, a, b, c, m1[4], 37, 11);
        rounds!(abef, cdgh, w2_1, 1);
        w2_0 = _mm_sha256msg1_epu32(w2_0, w2_1);
        hh!(c, d, a, b, m1[7], 38, 16);
        hh!(b, c, d, a, m1[10], 39, 23);
        hh!(a, b, c, d, m1[13], 40, 4);
        rounds!(abef, cdgh, w2_2, 2);
        w2_1 = _mm_sha256msg1_epu32(w2_1, w2_2);
        hh!(d, a, b, c, m1[0], 41, 11);
        hh!(c, d, a, b, m1[3], 42, 16);
        hh!(b, c, d, a, m1[6], 43, 23);
        rounds!(abef, cdgh, w2_3, 3);
        extend!(w2_0, w2_3, w2_2);
        w2_2 = _mm_sha256msg1_epu32(w2_2, w2_3);
        hh!(a, b, c, d, m1[9], 44, 4);
        hh!(d, a, b, c, m1[12], 45, 11);
        hh!(c, d, a, b, m1[15], 46, 16);
        rounds!(abef, cdgh, w2_0, 4);
        extend!(w2_1, w2_0, w2_3);
        w2_3 = _mm_sha256msg1_epu32(w2_3, w2_0);
        hh!(b, c, d, a, m1[2], 47, 23);
        ii!(a, b, c, d, m1[0], 48, 6);
        ii!(d, a, b, c, m1[7], 49, 10);
        rounds!(abef, cdgh, w2_1, 5);
        extend!(w2_2, w2_1, w2_0);
        w2_0 = _mm_sha256msg1_epu32(w2_0, w2_1);
        ii!(c, d, a, b, m1[14], 50, 15);
        ii!(b, c, d, a, m1[5], 51, 21);
        ii!(a, b, c, d, m1[12], 52, 6);
        rounds!(abef, cdgh, w2_2, 6);
        extend!(w2_3, w2_2, w2_1);
        w2_1 = _mm_sha256msg1_epu32(w2_1, w2_2);
        ii!(d, a, b, c, m1[3], 53, 10);
        ii!(c, d, a, b, m1[10], 54, 15);
        ii!(b, c, d, a, m1[1], 55, 21);
        rounds!(abef, cdgh, w2_3, 7);
        extend!(w2_0, w2_3, w2_2);
        w2_2 = _mm_sha256msg1_epu32(w2_2, w2_3);
        ii!(a, b, c, d, m1[8], 56, 6);
        ii!(d, a, b, c, m1[15], 57, 10);
        ii!(c, d, a, b, m1[6], 58, 15);
        rounds!(abef, cdgh, w2_0, 8);
        extend!(w2_1, w2_0, w2_3);
        w2_3 = _mm_sha256msg1_epu32(w2_3, w2_0);
        ii!(b, c, d, a, m1[13], 59, 21);
        ii!(a, b, c, d, m1[4], 60, 6);
        ii!(d, a, b, c, m1[11], 61, 10);
        rounds!(abef, cdgh, w2_1, 9);
        extend!(w2_2, w2_1, w2_0);
        w2_0 = _mm_sha256msg1_epu32(w2_0, w2_1);
        ii!(c, d, a, b, m1[2], 62, 15);
        ii!(b, c, d, a, m1[9], 63, 21);
        a = a.wrapping_add(saved_blk.0);
        b = b.wrapping_add(saved_blk.1);
        c = c.wrapping_add(saved_blk.2);
        d = d.wrapping_add(saved_blk.3);
        let saved_blk = (a, b, c, d);
        ff!(a, b, c, d, m2[0], 0, 7);
        rounds!(abef, cdgh, w2_2, 10);
        extend!(w2_3, w2_2, w2_1);
        w2_1 = _mm_sha256msg1_epu32(w2_1, w2_2);
        ff!(d, a, b, c, m2[1], 1, 12);
        ff!(c, d, a, b, m2[2], 2, 17);
        ff!(b, c, d, a, m2[3], 3, 22);
        rounds!(abef, cdgh, w2_3, 11);
        extend!(w2_0, w2_3, w2_2);
        w2_2 = _mm_sha256msg1_epu32(w2_2, w2_3);
        ff!(a, b, c, d, m2[4], 4, 7);
        ff!(d, a, b, c, m2[5], 5, 12);
        ff!(c, d, a, b, m2[6], 6, 17);
        rounds!(abef, cdgh, w2_0, 12);
        extend!(w2_1, w2_0, w2_3);
        w2_3 = _mm_sha256msg1_epu32(w2_3, w2_0);
        ff!(b, c, d, a, m2[7], 7, 22);
        ff!(a, b, c, d, m2[8], 8, 7);
        ff!(d, a, b, c, m2[9], 9, 12);
        rounds!(abef, cdgh, w2_1, 13);
        extend!(w2_2, w2_1, w2_0);
        ff!(c, d, a, b, m2[10], 10, 17);
        ff!(b, c, d, a, m2[11], 11, 22);
        ff!(a, b, c, d, m2[12], 12, 7);
        rounds!(abef, cdgh, w2_2, 14);
        extend!(w2_3, w2_2, w2_1);
        ff!(d, a, b, c, m2[13], 13, 12);
        ff!(c, d, a, b, m2[14], 14, 17);
        ff!(b, c, d, a, m2[15], 15, 22);
        rounds!(abef, cdgh, w2_3, 15);
        abef = _mm_add_epi32(abef, abef_saved2);
        cdgh = _mm_add_epi32(cdgh, cdgh_saved2);
        gg!(a, b, c, d, m2[1], 16, 5);
        gg!(d, a, b, c, m2[6], 17, 9);
        gg!(c, d, a, b, m2[11], 18, 14);
        let (abef_saved3, cdgh_saved3) = (abef, cdgh);
        let mut w3_0 = load(&s[3], 0);
        let mut w3_1 = load(&s[3], 1);
        let mut w3_2 = load(&s[3], 2);
        let mut w3_3 = load(&s[3], 3);
        rounds!(abef, cdgh, w3_0, 0);
        gg!(b, c, d, a, m2[0], 19, 20);
        gg!(a, b, c, d, m2[5], 20, 5);
        gg!(d, a, b, c, m2[10], 21, 9);
        rounds!(abef, cdgh, w3_1, 1);
        w3_0 = _mm_sha256msg1_epu32(w3_0, w3_1);
        gg!(c, d, a, b, m2[15], 22, 14);
        gg!(b, c, d, a, m2[4], 23, 20);
        gg!(a, b, c, d, m2[9], 24, 5);
        rounds!(abef, cdgh, w3_2, 2);
        w3_1 = _mm_sha256msg1_epu32(w3_1, w3_2);
        gg!(d, a, b, c, m2[14], 25, 9);
        gg!(c, d, a, b, m2[3], 26, 14);
        gg!(b, c, d, a, m2[8], 27, 20);
        rounds!(abef, cdgh, w3_3, 3);
        extend!(w3_0, w3_3, w3_2);
        w3_2 = _mm_sha256msg1_epu32(w3_2, w3_3);
        gg!(a, b, c, d, m2[13], 28, 5);
        gg!(d, a, b, c, m2[2], 29, 9);
        gg!(c, d, a, b, m2[7], 30, 14);
        rounds!(abef, cdgh, w3_0, 4);
        extend!(w3_1, w3_0, w3_3);
        w3_3 = _mm_sha256msg1_epu32(w3_3, w3_0);
        gg!(b, c, d, a, m2[12], 31, 20);
        hh!(a, b, c, d, m2[5], 32, 4);
        hh!(d, a, b, c, m2[8], 33, 11);
        rounds!(abef, cdgh, w3_1, 5);
        extend!(w3_2, w3_1, w3_0);
        w3_0 = _mm_sha256msg1_epu32(w3_0, w3_1);
        hh!(c, d, a, b, m2[11], 34, 16);
        hh!(b, c, d, a, m2[14], 35, 23);
        hh!(a, b, c, d, m2[1], 36, 4);
        rounds!(abef, cdgh, w3_2, 6);
        extend!(w3_3, w3_2, w3_1);
        w3_1 = _mm_sha256msg1_epu32(w3_1, w3_2);
        hh!(d, a, b, c, m2[4], 37, 11);
        hh!(c, d, a, b, m2[7], 38, 16);
        hh!(b, c, d, a, m2[10], 39, 23);
        rounds!(abef, cdgh, w3_3, 7);
        extend!(w3_0, w3_3, w3_2);
        w3_2 = _mm_sha256msg1_epu32(w3_2, w3_3);
        hh!(a, b, c, d, m2[13], 40, 4);
        hh!(d, a, b, c, m2[0], 41, 11);
        hh!(c, d, a, b, m2[3], 42, 16);
        rounds!(abef, cdgh, w3_0, 8);
        extend!(w3_1, w3_0, w3_3);
        w3_3 = _mm_sha256msg1_epu32(w3_3, w3_0);
        hh!(b, c, d, a, m2[6], 43, 23);
        hh!(a, b, c, d, m2[9], 44, 4);
        hh!(d, a, b, c, m2[12], 45, 11);
        rounds!(abef, cdgh, w3_1, 9);
        extend!(w3_2, w3_1, w3_0);
        w3_0 = _mm_sha256msg1_epu32(w3_0, w3_1);
        hh!(c, d, a, b, m2[15], 46, 16);
        hh!(b, c, d, a, m2[2], 47, 23);
        ii!(a, b, c, d, m2[0], 48, 6);
        rounds!(abef, cdgh, w3_2, 10);
        extend!(w3_3, w3_2, w3_1);
        w3_1 = _mm_sha256msg1_epu32(w3_1, w3_2);
        ii!(d, a, b, c, m2[7], 49, 10);
        ii!(c, d, a, b, m2[14], 50, 15);
        ii!(b, c, d, a, m2[5], 51, 21);
        rounds!(abef, cdgh, w3_3, 11);
        extend!(w3_0, w3_3, w3_2);
        w3_2 = _mm_sha256msg1_epu32(w3_2, w3_3);
        ii!(a, b, c, d, m2[12], 52, 6);
        ii!(d, a, b, c, m2[3], 53, 10);
        ii!(c, d, a, b, m2[10], 54, 15);
        rounds!(abef, cdgh, w3_0, 12);
        extend!(w3_1, w3_0, w3_3);
        w3_3 = _mm_sha256msg1_epu32(w3_3, w3_0);
        ii!(b, c, d, a, m2[1], 55, 21);
        ii!(a, b, c, d, m2[8], 56, 6);
        ii!(d, a, b, c, m2[15], 57, 10);
        rounds!(abef, cdgh, w3_1, 13);
        extend!(w3_2, w3_1, w3_0);
        ii!(c, d, a, b, m2[6], 58, 15);
        ii!(b, c, d, a, m2[13], 59, 21);
        ii!(a, b, c, d, m2[4], 60, 6);
        rounds!(abef, cdgh, w3_2, 14);
        extend!(w3_3, w3_2, w3_1);
        ii!(d, a, b, c, m2[11], 61, 10);
        ii!(c, d, a, b, m2[2], 62, 15);
        ii!(b, c, d, a, m2[9], 63, 21);
        a = a.wrapping_add(saved_blk.0);
        b = b.wrapping_add(saved_blk.1);
        c = c.wrapping_add(saved_blk.2);
        d = d.wrapping_add(saved_blk.3);
        rounds!(abef, cdgh, w3_3, 15);
        abef = _mm_add_epi32(abef, abef_saved3);
        cdgh = _mm_add_epi32(cdgh, cdgh_saved3);
    }
    *md5 = [a, b, c, d];
    let feba = _mm_shuffle_epi32(abef, 0x1b);
    let dchg = _mm_shuffle_epi32(cdgh, 0xb1);
    _mm_storeu_si128(sha.as_mut_ptr().cast(), _mm_blend_epi16(feba, dchg, 0xf0));
    _mm_storeu_si128(
        sha.as_mut_ptr().add(4).cast(),
        _mm_alignr_epi8(dchg, feba, 8),
    );
}
